// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package payment

import (
	"context"
	"github.com/mercor/payment-service/internal/payment/repository"
	"github.com/mercor/payment-service/internal/payment/service"
	"github.com/mercor/payment-service/pkg/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*PaymentController, error) {
	paymentLineRepository := repository.NewPaymentRepository(db)
	paymentService := service.NewPaymentService(paymentLineRepository)
	paymentController := NewPaymentController(paymentService)
	return paymentController, nil
}
