// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package job

import (
	"context"
	repository2 "github.com/mercor/payment-service/internal/company/repository"
	repository3 "github.com/mercor/payment-service/internal/contractor/repository"
	"github.com/mercor/payment-service/internal/job/repository"
	"github.com/mercor/payment-service/internal/job/service"
	"github.com/mercor/payment-service/pkg/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*Controller, error) {
	jobRepositoryInterface := repository.NewJobRepository(db)
	companyRepository := repository2.NewCompanyRepository(db)
	contractorRepository := repository3.NewContractorRepository(db)
	service := job.NewService(jobRepositoryInterface, companyRepository, contractorRepository)
	controller := NewController(service)
	return controller, nil
}
