// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package timelog

import (
	"context"
	"github.com/mercor/payment-service/internal/timelog/repository"
	"github.com/mercor/payment-service/internal/timelog/service"
	"github.com/mercor/payment-service/pkg/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*TimelogController, error) {
	timeLogRepositoryInterface := repository.NewTimelogRepository(db)
	timelogService := service.NewTimelogService(timeLogRepositoryInterface)
	timelogController := NewTimelogController(timelogService)
	return timelogController, nil
}
