// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package contractor

import (
	"context"
	"github.com/mercor/payment-service/internal/contractor/repository"
	"github.com/mercor/payment-service/internal/contractor/service"
	"github.com/mercor/payment-service/pkg/db/sql/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) (*Controller, error) {
	contractorRepository := repository.NewContractorRepository(db)
	contractorService := service.NewContractorService(contractorRepository)
	controller := NewController(contractorService)
	return controller, nil
}
